
name: Git Decrypt Action
on: 
  workflow_call:
    secrets:
      GIT_CRYPT_KEY:
        required: true

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Decrypt
        run: | 
          sudo apt-get update && sudo apt-get install -y git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git-crypt unlock -
