name: Terraform Apply

on:
  push:
    tags:
      - 'terraform_v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

jobs:
  validation:
  uses: ./.github/workflows/terraform_validate.yaml

  apply:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
